version: 2

jobs:
  test:
    macos:
      xcode: "9.3"
    steps:
      - checkout
      - run: bundle install
      - run: ./scripts/macOS.sh
      - run: ./scripts/iOS-11.3.sh
      - run: ./scripts/iOS-10.3.1.sh
      - run: ./scripts/tvOS-11.3.sh
      - run: ./scripts/tvOS-10.3.sh
      - run: ./scripts/watchOS-4.3.sh
      - run: bundle exec pod lib lint

  carthage-build:
    macos:
      xcode: "9.3"
    steps:
      - checkout
      - run:
          name: Update homebrew dependencies
          command: brew update 1> /dev/null 2> /dev/null
      - run:
          name: Update Carthage
          command: brew outdated carthage || (brew uninstall carthage --force; HOMEBREW_NO_AUTO_UPDATE=1 brew install carthage --force-bottle)
      - run: carthage build --no-skip-current && for platform in Mac iOS tvOS watchOS; do test -d Carthage/Build/${platform}/BonMot.framework || exit 1; done

  deploy-to-cocoapods:
    macos:
      xcode: "9.3"
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec pod trunk push

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test
      - carthage-build
#      - deploy-to-cocoapods:
#          requires:
#            - test
#          filters:
#            tags:
#              only: /\d+(\.\d+)*(-.*)*/
