version: 2

jobs:
  test-xcode-9-3:
    macos:
      xcode: "9.3.0"
    steps:
      - checkout
      - run:
          name: Install CocoaPods Specs Repo
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run: bundle install
      - run: ./scripts/macOS.sh
      - run: ./scripts/iOS-11.3.sh
      - run: ./scripts/tvOS-11.3.sh
      - run: ./scripts/watchOS-4.3.sh
      - run: bundle exec pod lib lint
  test-xcode-9-2:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run: bundle install
      - run: ./scripts/macOS.sh
      - run: ./scripts/iOS-10.3.1.sh
      - run: ./scripts/tvOS-10.2.sh

  carthage-build:
    macos:
      xcode: "9.3.0"
    steps:
      - checkout
      - run:
          name: Update homebrew dependencies
          command: brew update 1> /dev/null 2> /dev/null
      - run:
          name: Update Carthage
          command: brew outdated carthage || (brew uninstall carthage --force; HOMEBREW_NO_AUTO_UPDATE=1 brew install carthage --force-bottle)
      - run: carthage build --no-skip-current && for platform in Mac iOS tvOS watchOS; do test -d Carthage/Build/${platform}/BonMot.framework || exit 1; done

  deploy-to-cocoapods:
    macos:
      xcode: "9.3.0"
    steps:
      - checkout
      - run:
          name: Install CocoaPods Specs Repo
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run: bundle install
      - run: bundle exec pod trunk push

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test-xcode-9-3:
          filters:
            tags:
              only: /.*/
      - test-xcode-9-2:
          filters:
            tags:
              only: /.*/
      - carthage-build:
          filters:
            tags:
              only: /.*/
      - deploy-to-cocoapods:
          requires:
            - test-xcode-9-3
            - test-xcode-9-2
            - carthage-build
          filters:
            tags:
              only: /\d+(\.\d+)*(-.*)*/
            branches:
              ignore: /.*/
